FROM node:15.2.1

WORKDIR /app/server

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source
COPY . .

# Install app dependencies
RUN npm install

EXPOSE 8080

CMD [ "npm", "run", "dev" ]

