FROM node:15.2.1

WORKDIR /app/server

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./

# Bundle app source
COPY . .

# Install app dependencies
RUN npm install

# Build app
RUN npm run build

EXPOSE 5000

CMD [ "npm", "start" ]

